var hierarchy =
[
    [ "guanaqo::any_ptr", "classguanaqo_1_1any__ptr.html", null ],
    [ "guanaqo::AtomicStopSignal", "classguanaqo_1_1AtomicStopSignal.html", null ],
    [ "guanaqo::BasicVTable", "structguanaqo_1_1BasicVTable.html", null ],
    [ "guanaqo::CircularIndexIterator&lt; IndexT &gt;", "structguanaqo_1_1CircularIndexIterator.html", null ],
    [ "guanaqo::CircularIndices&lt; IndexT &gt;", "structguanaqo_1_1CircularIndices.html", null ],
    [ "guanaqo::CircularRange&lt; IndexT &gt;", "classguanaqo_1_1CircularRange.html", null ],
    [ "guanaqo::class_from_member_ptr_impl&lt; M &gt;", "namespaceguanaqo.html#structguanaqo_1_1class__from__member__ptr__impl", null ],
    [ "guanaqo::class_from_member_ptr_impl&lt; Ret(C::*)(Args...) const &gt;", "namespaceguanaqo.html#structguanaqo_1_1class__from__member__ptr__impl_3_01Ret_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4", null ],
    [ "guanaqo::class_from_member_ptr_impl&lt; Ret(C::*)(Args...)&gt;", "namespaceguanaqo.html#structguanaqo_1_1class__from__member__ptr__impl_3_01Ret_07C_1_1_5_08_07Args_8_8_8_08_4", null ],
    [ "guanaqo::copyable_unique_ptr&lt; T &gt;", "structguanaqo_1_1copyable__unique__ptr.html", null ],
    [ "guanaqo::CopyMoveDestroyVTable", "group__type__erasure.html#structguanaqo_1_1CopyMoveDestroyVTable", null ],
    [ "guanaqo::default_stride&lt; S &gt;", "group__linalg__views.html#structguanaqo_1_1default__stride", null ],
    [ "guanaqo::default_stride&lt; S &gt;", "structguanaqo_1_1default__stride_3_01S_01_4.html", null ],
    [ "guanaqo::detail::dummy&lt;... &gt;", "namespaceguanaqo_1_1detail.html#structguanaqo_1_1detail_1_1dummy", null ],
    [ "guanaqo::detail::Launderer&lt; Class, ExtraArgs &gt;", "structguanaqo_1_1detail_1_1Launderer.html", null ],
    [ "guanaqo::detail::lut&lt; Args &gt;", "namespaceguanaqo_1_1detail.html#structguanaqo_1_1detail_1_1lut", null ],
    [ "guanaqo::detail::lut&lt; Arr, Ns... &gt;", "structguanaqo_1_1detail_1_1lut_3_01Arr_00_01Ns_8_8_8_01_4.html", null ],
    [ "guanaqo::detail::lut&lt; N, Ns... &gt;", "structguanaqo_1_1detail_1_1lut_3_01N_00_01Ns_8_8_8_01_4.html", null ],
    [ "guanaqo::detail::lut&lt;&gt;", "structguanaqo_1_1detail_1_1lut_3_4.html", null ],
    [ "guanaqo::detail::optional_function&lt; class, VTable &gt;", "namespaceguanaqo_1_1detail.html#structguanaqo_1_1detail_1_1optional__function", null ],
    [ "guanaqo::detail::optional_function&lt; R(Args...) const, VTable &gt;", "structguanaqo_1_1detail_1_1optional__function_3_01R_07Args_8_8_8_08_01const_00_01VTable_01_4.html", null ],
    [ "guanaqo::detail::optional_function&lt; R(Args...), VTable &gt;", "structguanaqo_1_1detail_1_1optional__function_3_01R_07Args_8_8_8_08_00_01VTable_01_4.html", null ],
    [ "guanaqo::detail::required_function&lt; class &gt;", "namespaceguanaqo_1_1detail.html#structguanaqo_1_1detail_1_1required__function", null ],
    [ "guanaqo::detail::required_function&lt; R(Args...) const &gt;", "structguanaqo_1_1detail_1_1required__function_3_01R_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "guanaqo::detail::required_function&lt; R(Args...)&gt;", "structguanaqo_1_1detail_1_1required__function_3_01R_07Args_8_8_8_08_4.html", null ],
    [ "guanaqo::DynamicLoadFlags", "structguanaqo_1_1DynamicLoadFlags.html", null ],
    [ "guanaqo::enumerate_t&lt; Rng &gt;::iter_t", "structguanaqo_1_1enumerate__t_1_1iter__t.html", null ],
    [ "guanaqo::enumerate_t&lt; Rng &gt;::sentinel_t", "structguanaqo_1_1enumerate__t.html#structguanaqo_1_1enumerate__t_1_1sentinel__t", null ],
    [ "guanaqo::first_type_or_void&lt; Pack &gt;", "group__core.html#structguanaqo_1_1first__type__or__void", null ],
    [ "guanaqo::first_type_or_void&lt; First, Pack... &gt;", "group__core.html#structguanaqo_1_1first__type__or__void_3_01First_00_01Pack_8_8_8_01_4", null ],
    [ "guanaqo::first_type_or_void&lt;&gt;", "group__core.html#structguanaqo_1_1first__type__or__void_3_4", null ],
    [ "guanaqo::io::CSVReader&lt; F &gt;", "structguanaqo_1_1io_1_1CSVReader.html", null ],
    [ "guanaqo::iter_range_adapter&lt; It &gt;", "structguanaqo_1_1iter__range__adapter.html", null ],
    [ "guanaqo::iter_range_adapter&lt; It &gt;::sentinel_t", "structguanaqo_1_1iter__range__adapter.html#structguanaqo_1_1iter__range__adapter_1_1sentinel__t", null ],
    [ "guanaqo::join_opt", "group__strings.html#structguanaqo_1_1join__opt", null ],
    [ "guanaqo::join_quote_opt", "group__strings.html#structguanaqo_1_1join__quote__opt", null ],
    [ "guanaqo::last_type&lt; First, Pack &gt;", "group__core.html#structguanaqo_1_1last__type", null ],
    [ "guanaqo::last_type&lt; Only &gt;", "group__core.html#structguanaqo_1_1last__type_3_01Only_01_4", null ],
    [ "guanaqo::linalg::MatrixView&lt; T &gt;", "structguanaqo_1_1linalg_1_1MatrixView.html", null ],
    [ "guanaqo::linalg::Sparsity", "structguanaqo_1_1linalg_1_1Sparsity.html", null ],
    [ "guanaqo::linalg::sparsity::Dense", "group__linalg__sparsity.html#structguanaqo_1_1linalg_1_1sparsity_1_1Dense", null ],
    [ "guanaqo::linalg::sparsity::detail::ConverterVariantHelper&lt; To, class &gt;", "namespaceguanaqo_1_1linalg_1_1sparsity_1_1detail.html#structguanaqo_1_1linalg_1_1sparsity_1_1detail_1_1ConverterVariantHelper", null ],
    [ "guanaqo::linalg::sparsity::detail::ConverterVariantHelper&lt; To, std::variant&lt; Froms... &gt; &gt;", "namespaceguanaqo_1_1linalg_1_1sparsity_1_1detail.html#structguanaqo_1_1linalg_1_1sparsity_1_1detail_1_1ConverterVariantHelper_3_01To_00_01std_1_1variant_3_01Froms_8_8_8_01_4_01_4", null ],
    [ "guanaqo::linalg::sparsity::SparseCOO&lt; Index &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparseCOO.html", null ],
    [ "guanaqo::linalg::sparsity::SparseCSC&lt; Index, StorageIndex &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparseCSC.html", null ],
    [ "guanaqo::linalg::sparsity::Sparsity", "structguanaqo_1_1linalg_1_1sparsity_1_1Sparsity.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConversionRequest&lt; To &gt;", "group__linalg__sparsity__conv.html#structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConversionRequest", null ],
    [ "guanaqo::linalg::sparsity::SparsityConversionRequest&lt; Dense &gt;", "group__linalg__sparsity__conv.html#structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConversionRequest_3_01Dense_01_4", null ],
    [ "guanaqo::linalg::sparsity::SparsityConversionRequest&lt; SparseCOO&lt; Index &gt; &gt;", "group__linalg__sparsity__conv.html#structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConversionRequest_3_01SparseCOO_3_01Index_01_4_01_4", null ],
    [ "guanaqo::linalg::sparsity::SparsityConversionRequest&lt; SparseCSC&lt; Index, StorageIndex &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConversionRequest_3_01SparseCSC_3_01Index_00_01StorageIndex_01_4_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; From, To &gt;", "group__linalg__sparsity__conv.html#structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; Dense, Dense &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01Dense_00_01Dense_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; Dense, SparseCOO&lt; Index &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01Dense_00_01SparseCOO_3_01Index_01_4_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; Dense, SparseCSC&lt; Index, StorageIndex &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01Dense_00_01SparseCSC_3_01Index_00_01StorageIndex_01_4_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCOO&lt; Index &gt;, Dense &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCOO_3_01Index_01_4_00_01Dense_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCOO&lt; IndexFrom &gt;, SparseCOO&lt; IndexTo &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCOO_3_01IndexFrom_01_4_00_01SparseCOO_3_01IndexTo_01_4_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCOO&lt; IndexFrom &gt;, SparseCSC&lt; IndexTo, StorageIndexTo &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCOO_3_01IndexFrom_01_4_00_01S67b6f2c0f3c4edbe7a0b5208ada2b096.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCSC&lt; Index, StorageIndex &gt;, Dense &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCSC_3_01Index_00_01StorageIndex_01_4_00_01Dense_01_4.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCSC&lt; IndexFrom, StorageIndexFrom &gt;, SparseCOO&lt; IndexTo &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCSC_3_01IndexFrom_00_01Storagd7eacb656b7048a626db1b5d44289905.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; SparseCSC&lt; IndexFrom, StorageIndexFrom &gt;, SparseCSC&lt; IndexTo, StorageIndexTo &gt; &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01SparseCSC_3_01IndexFrom_00_01Storag482666d5a5943ffa42fa943282e59db2.html", null ],
    [ "guanaqo::linalg::sparsity::SparsityConverter&lt; Sparsity, To &gt;", "structguanaqo_1_1linalg_1_1sparsity_1_1SparsityConverter_3_01Sparsity_00_01To_01_4.html", null ],
    [ "guanaqo::MatrixView&lt; T, I, S, O &gt;", "structguanaqo_1_1MatrixView.html", null ],
    [ "guanaqo::MatrixView&lt; T, I, S, O &gt;::PlainMatrixView", "structguanaqo_1_1MatrixView.html#structguanaqo_1_1MatrixView_1_1PlainMatrixView", null ],
    [ "guanaqo::MaxHistory&lt; T &gt;", "classguanaqo_1_1MaxHistory.html", null ],
    [ "guanaqo::noop_delete&lt; T &gt;", "structguanaqo_1_1noop__delete.html", null ],
    [ "guanaqo::pcm::detail::ScopedCounters", "structguanaqo_1_1pcm_1_1detail_1_1ScopedCounters.html", null ],
    [ "guanaqo::pcm::ScopedCounters&lt; F &gt;", "structguanaqo_1_1pcm_1_1ScopedCounters.html", null ],
    [ "guanaqo::pcm::ThreadPerfCounters", "group__trace__pcm.html#structguanaqo_1_1pcm_1_1ThreadPerfCounters", null ],
    [ "guanaqo::PrintMatrixView&lt; T &gt;", "classguanaqo_1_1PrintMatrixView.html", null ],
    [ "guanaqo::PrintOpts", "group__io.html#structguanaqo_1_1PrintOpts", null ],
    [ "guanaqo::ReverseCircularIndexIterator&lt; IndexT &gt;", "structguanaqo_1_1ReverseCircularIndexIterator.html", null ],
    [ "guanaqo::ReverseCircularRange&lt; IndexT &gt;", "classguanaqo_1_1ReverseCircularRange.html", null ],
    [ "guanaqo::scoped_ostream_redirect", "classguanaqo_1_1scoped__ostream__redirect.html", null ],
    [ "guanaqo::set_intersection_iterable&lt; R1, R2, Comp, Proj1, Proj2 &gt;::iter_t&lt; I1, S1, I2, S2 &gt;", "structguanaqo_1_1set__intersection__iterable_1_1iter__t.html", null ],
    [ "guanaqo::set_intersection_iterable&lt; R1, R2, Comp, Proj1, Proj2 &gt;::sentinel_t", "structguanaqo_1_1set__intersection__iterable.html#structguanaqo_1_1set__intersection__iterable_1_1sentinel__t", null ],
    [ "guanaqo::shared_any_ptr", "classguanaqo_1_1shared__any__ptr.html", null ],
    [ "guanaqo::tag_invoke_fn_ns::tag_invoke_fn", "structguanaqo_1_1tag__invoke__fn__ns_1_1tag__invoke__fn.html", null ],
    [ "guanaqo::Timed&lt; T &gt;", "group__timing.html#structguanaqo_1_1Timed", null ],
    [ "guanaqo::Timed&lt; std::chrono::duration&lt; Rep, Period &gt; &gt;", "structguanaqo_1_1Timed_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_01_4.html", null ],
    [ "guanaqo::Timed&lt; TimingsCPU &gt;", "structguanaqo_1_1Timed_3_01TimingsCPU_01_4.html", null ],
    [ "guanaqo::TimingsCPU", "group__timing.html#structguanaqo_1_1TimingsCPU", null ],
    [ "guanaqo::trace::ScopedLinalgCounters", "structguanaqo_1_1trace_1_1ScopedLinalgCounters.html", null ],
    [ "guanaqo::TraceLogger", "structguanaqo_1_1TraceLogger.html", null ],
    [ "guanaqo::TraceLogger::Log", "structguanaqo_1_1TraceLogger_1_1Log.html", null ],
    [ "guanaqo::TraceLogger::ScopedLog", "structguanaqo_1_1TraceLogger_1_1ScopedLog.html", null ],
    [ "guanaqo::TypeErased&lt; VTable, Allocator, SmallBufferSize &gt;", "classguanaqo_1_1TypeErased.html", null ],
    [ "guanaqo::TypeErased&lt; VTable, Allocator, SmallBufferSize &gt;::Deallocator", "structguanaqo_1_1TypeErased_1_1Deallocator.html", null ],
    [ "guanaqo::with_index_type_t&lt; I &gt;", "namespaceguanaqo.html#structguanaqo_1_1with__index__type__t", null ],
    [ "nanobind::detail::type_caster&lt; guanaqo::MatrixView&lt; T, I, S, O &gt; &gt;", "structnanobind_1_1detail_1_1type__caster_3_01guanaqo_1_1MatrixView_3_01T_00_01I_00_01S_00_01O_01_4_01_4.html", null ],
    [ "std::false_type", null, [
      [ "guanaqo::is_complex_float< std::complex< T > >", "structguanaqo_1_1is__complex__float_3_01std_1_1complex_3_01T_01_4_01_4.html", null ],
      [ "guanaqo::is_complex_float< T >", "structguanaqo_1_1is__complex__float.html", null ]
    ] ],
    [ "std::invalid_argument", null, [
      [ "guanaqo::invalid_duration_units", "structguanaqo_1_1invalid__duration__units.html", null ],
      [ "guanaqo::invalid_duration_value", "structguanaqo_1_1invalid__duration__value.html", null ]
    ] ],
    [ "std::logic_error", null, [
      [ "guanaqo::bad_type_erased_constness", "classguanaqo_1_1bad__type__erased__constness.html", null ],
      [ "guanaqo::bad_type_erased_type", "classguanaqo_1_1bad__type__erased__type.html", null ],
      [ "guanaqo::linalg::sparsity::unsupported_conversion", "structguanaqo_1_1linalg_1_1sparsity_1_1unsupported__conversion.html", null ],
      [ "guanaqo::not_implemented_error", "structguanaqo_1_1not__implemented__error.html", null ]
    ] ],
    [ "std::ranges::view_interface", null, [
      [ "guanaqo::enumerate_t< Rng >", "structguanaqo_1_1enumerate__t.html", null ],
      [ "guanaqo::set_intersection_iterable< R1, R2, Comp, Proj1, Proj2 >", "structguanaqo_1_1set__intersection__iterable.html", null ]
    ] ],
    [ "std::remove_cvref_t", null, [
      [ "guanaqo::iter_range_adapter< It >::iter_t", "structguanaqo_1_1iter__range__adapter_1_1iter__t.html", null ]
    ] ],
    [ "std::runtime_error", null, [
      [ "guanaqo::blas::lapack_error", "structguanaqo_1_1blas_1_1lapack__error.html", null ],
      [ "guanaqo::dynamic_load_error", "structguanaqo_1_1dynamic__load__error.html", null ],
      [ "guanaqo::io::csv_read_error", "structguanaqo_1_1io_1_1csv__read__error.html", null ]
    ] ],
    [ "std::streambuf", null, [
      [ "guanaqo::callback_streambuf", "classguanaqo_1_1callback__streambuf.html", null ]
    ] ],
    [ "std::true_type", null, [
      [ "guanaqo::is_complex_float< std::complex< T > >", "structguanaqo_1_1is__complex__float_3_01std_1_1complex_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "Ts...", null, [
      [ "guanaqo::linalg::sparsity::detail::overloaded< Ts >", "structguanaqo_1_1linalg_1_1sparsity_1_1detail_1_1overloaded.html", null ]
    ] ]
];